### ISSUE TITLE
(question) Production ready?

### ISSUE THREAD

**Issue by jadbox** [alanctgardner/gogen-avro#14]
I'm currently evaluating the fastest method to use Avro with Go, and this seems like the ideal lib. Does anyone have experience working with this in production setting? Our particular setting is using Avro over Kafka with relatively simple schemas.

**Comment by alanctgardner** [comment]
We use gogen-avro in production at my day job, encoding millions of events every day to publish to Kafka. It sounds like a similar use case. The schema we use is also open source: https://github.com/osso-project/osso

Standard open-source caveats apply: I work on this project in my free time, so support is best effort. My employer doesn't make any guarantees about your use case, etc. etc. I try to be responsive about any issues and provide a sane release schedule so things won't break on you. If you're OK with providing your schema and some sample data I could also add it to the integration tests.

**Comment by jadbox** [comment]
Cool thanks for the overview
