### ISSUE TITLE
Accessing schema metadata fields

### ISSUE THREAD

**Issue by rikonor** [alanctgardner/gogen-avro#19]
Hey Alan,

Is it possible somehow to access metadata fields on a schema?

Notice the `uuid_keys` metadata field on this schema:

```json
[
  { "name": "ip_address", "type": "fixed", "size": 16 },
  {
      "type": "record",
      "name": "event",
      "subject": "event",
      "fields": [
          { "name": "id", "type": "string" },
          { "name": "domain", "type": "string" },
          { "name": "start_ip_address", "type": "ip_address" },
          { "name": "end_ip_address", "type": "ip_address" }
      ],
      "uuid_keys": [ "domain" ]
  }
]
```

Originally, we were using that field to generate a `GenerateID` method on the record struct.
Although, after the current changes, it seems a bit more problematic to get that field.
I tried implementing it again in [here](https://github.com/securityscorecard/gogen-avro/commit/8abfaf31809b91ae679bc47daf42ec506d52d84d#diff-2064fdd07d1b22db8e40902b8c2436edR225) but I can't access that field anymore.

Another approach which could work is to generate this function on the fly (and not making any changes to `gogen-avro`) but for that to happen the `Serializable`'s `Schema` method would have to return metadata fields as well, which it does not seem to do at the moment.

**Comment by alanctgardner** [comment]
I made a change so the `Schema` method now includes metadata fields, let me know if that works for you. There's an example in this test: https://github.com/alanctgardner/gogen-avro/blob/master/test/union-root/container_test.go#L38-L57

**Comment by rikonor** [comment]
Tested and works great, thanks!
