### ISSUE TITLE
Record Schema method become camel case

### ISSUE THREAD

**Issue by rikonor** [alanctgardner/gogen-avro#20]
Hi,

Currently, when generating the struct for a record, field names get converted to camel case, e.g. `ip_address` -> `IPAddress`. This is so struct field names are more Go idiomatic.

That said, I also noticed that the generated Schema method of a record will contain the CamelCase field names, instead of the original names. This means that the schema loses the original casing of the names.

**Comment by alanctgardner** [comment]
Thanks for reporting this Or! It should be fixed in master now. I'm planning to add more unit tests around the container file schemas but I haven't found time yet.

**Comment by rikonor** [comment]
Great, thanks very much Alan!
