### ISSUE TITLE
Handling default values

### ISSUE THREAD

**Issue by rikonor** [alanctgardner/gogen-avro#25]
Hey Alan,

I noticed that `default` values don't seem to be handled at the moment (unless I'm missing something).

I generated code based on:
```
{
    "type": "record",
    "name": "example",
    "subject": "example",
    "fields": [
        {
            "name": "name",
            "type": "string"
        },
        {
            "name": "hobby",
            "type": "string",
            "default": "golf"
        }
    ]
}
```

Then ran:
```go
func main() {
	el := example.Example{
		Name: "Or",
		// Hobby: "PRs",
	}

	var buf bytes.Buffer
	if err := el.Serialize(&buf); err != nil {
		log.Fatal(err)
	}

	eln, err := example.DeserializeExample(&buf)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("%+v\n", eln)
}
```

which output:
```
&{Name:Or Hobby:}
```

If I uncomment the line above, I get a value as expected.

**Comment by alanctgardner** [comment]
Sorry about the slow reply. Default values don't work right now, I should have time in the next few days to add them.

**Comment by rikonor** [comment]
No worries. Thanks a lot for you work Alan!

**Comment by alanctgardner** [comment]
@rikonor Default values should work in master now - every Record struct has a constructor method that will set the values from the schema file. Let me know how it works for you!

**Comment by rikonor** [comment]
That's fantastic. Thank you very much @alanctgardner
