### ISSUE TITLE
Naming Conflicts in generated code

### ISSUE THREAD

**Issue by jtwatson** [alanctgardner/gogen-avro#28]
I just ran across an issue caused from the way that field names are generated where we end up with two fields with the same name, and obviously the go code will not compile.  

Example:
```
{
	"type": "record",
	"name": "PROFILE_INFO",
	"fields" : [
		{"name": "PERMRESCARD", "type": ["null", "string"]},
		{"name": "PERM_RES_CARD", "type": ["null", "string"]},
	]
}
```
The resulting struct will not compile:
```
type PROFILEINFO struct {
	PERMRESCARD     UnionNullString
	PERMRESCARD     UnionNullString
}
```
will not compile.

**Comment by alanctgardner** [comment]
@jtwatson Thanks for bringing this up! We were using snaker to convert names to idiomatic Go names, but it turns out that leads to name collisions in existing schemas (like this). 

I've made a change in master which should reduce the number of collisions for now. The

**Comment by jtwatson** [comment]
Looks like this will reduce the collisions to the least possible and still produce valid go names.  I have a project that is auto generating code that uses the go code generated by gogen-avro, so it is important for me long term that this is predictable.  I think I will start using your ```ToPublicName()``` function.

Thanks for the work you do!
