### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by asdine** [alanctgardner/gogen-avro#36]
The latest release has been released on March and since then there have been some useful additions.
Using gogen-avro with Glide or Dep make us use the 4.0.2 by default while installing the compiler using `go get` installs the latest commit.
Unfortunately, the code doesn't compile because of differences on some signatures.
I think it would be way easier if you created a new release with possibly prebuilt binaries. What do you think ?

**Comment by alanctgardner** [comment]
I cut a v5.0 that should do a better job of not breaking - all the references should be to the gopkg.in version rather than Github master. Let me know if it works better for you.

**Comment by asdine** [comment]
That's great ! Thank you !
