### ISSUE TITLE
Support for unions with records 

### ISSUE THREAD

**Issue by cweaver1321** [alanctgardner/gogen-avro#5]
The current implementation (decodeUnionDefinition) assumes that your unions will only contain a go string type. If you have a union with a type that is not primitive it fails. 

Error:
Decoded field err map[default:<nil> name:someId type:[null map[name:ID namespace:com.mystuff size:16 type:fixed]]] - Union members for someId is not of type strings

Schema file used:
[unionFailure.txt](https://github.com/alanctgardner/gogen-avro/files/238831/unionFailure.txt)

**Comment by alanctgardner** [comment]
This should be resolved now on master. Let me know if it works for you!

**Comment by alanctgardner** [comment]
@cweaver1321 I'm going to go ahead and close this, feel free to make a new issue if it isn't resolved.
